(function () {
  const archiveEl = document.getElementById('notice-archive');
  const GITHUB_API = 'https://api.github.com/repos/Parrocca/parrocca-msida/contents';
  const isEnglish = document.documentElement.lang === 'en';
  const NOTICE_FILE = isEnglish
    ? /^notice-(\d{4})-(\d{2})-(\d{2})\.(txt|jpe?g|png|webp|pdf)$/i
    : /^avviz-(\d{4})-(\d{2})-(\d{2})\.(txt|jpe?g|png|webp|pdf)$/i;
  const FALLBACK_FILES = isEnglish
    ? ['notice-2026-09-20.pdf','notice-2026-09-13.pdf','notice-2026-09-06.pdf']
    : ['avviz-2026-09-20.pdf','avviz-2026-09-13.pdf','avviz-2026-09-06.pdf','avviz-2026-08-30.txt'];
  function localItem(name){return {type:'file',name,download_url:'./'+encodeURIComponent(name)};}
  async function getFiles(){try{const r=await fetch(GITHUB_API+'?ts='+Date.now(),{headers:{Accept:'application/vnd.github+json'},cache:'no-store'});if(!r.ok)throw new Error();const f=(await r.json()).filter(x=>x.type==='file'&&NOTICE_FILE.test(x.name)).sort((a,b)=>b.name.localeCompare(a.name));if(f.length)return f;}catch(e){console.warn('Archive API fallback',e);}return FALLBACK_FILES.map(localItem).sort((a,b)=>b.name.localeCompare(a.name));}

  function esc(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function dateFromName(name){const m=name.match(NOTICE_FILE);if(!m)return '';const d=new Date(+m[1],+m[2]-1,+m[3]);return new Intl.DateTimeFormat(isEnglish?'en-GB':'mt-MT',{day:'numeric',month:'long',year:'numeric'}).format(d);}
  function parseText(text,fallback){const lines=text.trim().split(/\r?\n/);const n={data:fallback,titlu:isEnglish?'Parish Notices':'Avviżi Parrokkjali',sottotitlu:'',body:[]};let body=false;for(const raw of lines){const line=raw.trim();if(!body&&/^DATA:/i.test(line))n.data=line.replace(/^DATA:/i,'').trim();else if(!body&&/^(TITLU|TITOLU|TITLE):/i.test(line))n.titlu=line.replace(/^(TITLU|TITOLU|TITLE):/i,'').trim();else if(!body&&/^(SOTTOTITLU|SOTTOTITOLU|SUBTITLE):/i.test(line))n.sottotitlu=line.replace(/^(SOTTOTITLU|SOTTOTITOLU|SUBTITLE):/i,'').trim();else if(!body&&/^(TEST|TEXT):\s*$/i.test(line))body=true;else{body=true;n.body.push(raw);}}n.body=n.body.join('\n').trim();return n;}
  function paragraphs(body){return String(body||'').split(/\n\s*\n/).filter(Boolean).map(p=>`<p>${esc(p.trim()).replace(/\n/g,'<br>')}</p>`).join('');}
  async function loadItem(item){if(/\.txt$/i.test(item.name)){const r=await fetch(item.download_url+'?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error();return {item,notice:parseText(await r.text(),dateFromName(item.name)),type:'text'};}return {item,type:/\.pdf$/i.test(item.name)?'pdf':'image'};}
  function content(d){const date=dateFromName(d.item.name);if(d.type==='pdf'){const u='./'+encodeURIComponent(d.item.name);return `<article class="notice archive-card"><span class="pill">${esc(date)}</span><h3>${isEnglish?'Parish Notices':'Avviżi Parrokkjali'}</h3><p><a class="btn btn-primary" href="${u}" target="_blank" rel="noopener">${isEnglish?'Open Notices (PDF)':'Iftaħ l-Avviżi (PDF)'}</a></p></article>`;}if(d.type==='image'){return `<article class="notice archive-card"><span class="pill">${esc(date)}</span><h3>${isEnglish?'Parish Notice':'Avviż Parrokkjali'}</h3><a href="${d.item.download_url}" target="_blank" rel="noopener"><img class="auto-notice-image" src="${d.item.download_url}" alt="${esc(date)}" loading="lazy"></a></article>`;}return `<article class="notice archive-card">${d.notice.data?`<span class="pill">${esc(d.notice.data)}</span>`:''}<h3>${esc(d.notice.titlu)}</h3>${d.notice.sottotitlu?`<p><strong>${esc(d.notice.sottotitlu)}</strong></p>`:''}${paragraphs(d.notice.body)}</article>`;}
  async function load(){try{const files=await getFiles();const data=await Promise.all(files.map(loadItem));const archived=data.slice(1);archiveEl.innerHTML=archived.map(d=>{const label=d.type==='text'?(d.notice.data||''):dateFromName(d.item.name);const title=d.type==='text'?d.notice.titlu:(isEnglish?'Parish Notices':'Avviżi Parrokkjali');return `<details class="archive-item"><summary><span>${esc(label)}</span><strong>${esc(title)}</strong></summary><div class="archive-content">${content(d)}</div></details>`;}).join('')||`<p>${isEnglish?'No notices are currently available.':'Bħalissa m’hemmx avviżi fl-arkivju.'}</p>`;}catch(e){archiveEl.innerHTML=`<p>${isEnglish?'The archive could not be loaded. Please try again later.':'Ma rnexxilniex nuru l-arkivju. Erġa’ pprova aktar tard.'}</p>`;}}
  document.addEventListener('DOMContentLoaded',load);
})();
